source(file.path("R", "_helpers.R"))
ensure_dirs()

library(DESeq2)
library(adegenet)
library(readr)
library(dplyr)
library(tidyr)
library(ggplot2)
library(ggrepel)
library(patchwork)

# =============================================================================
# Physiological-transcriptomic decoupling index (PTDI)
#
# Workflow for each species:
# 1. Use the warming-responsive DEG set generated by R/10_prepare_deseq2_gene_sets.R.
# 2. VST-transform the raw counts of those genes.
# 3. Perform DAPC on the transcriptomic matrix and retain LD1–LD2 coordinates.
# 4. Perform PCA on seven standardized physiological traits and retain PC1–PC2.
# 5. Within each watering regime, calculate sample-level Euclidean distance from
#    each sample to the corresponding T0 centroid in transcriptomic (Dtrans) and
#    physiological (Dphys) space.
# 6. PTDI = Dtrans / Dphys. T0 is excluded from PTDI because it defines the
#    reference centroid, but T0 samples are retained for trajectory plots.
# =============================================================================

COUNT_PATHS <- c(
  Aj = Sys.getenv("AJ_RAW_COUNTS", unset = file.path("data", "expression", "Aj_raw_counts.tsv.gz")),
  Ce = Sys.getenv("CE_RAW_COUNTS", unset = file.path("data", "expression", "Ce_raw_counts.tsv.gz"))
)

phys_traits <- c("BMS_var", "Photo", "Cond", "MDA", "APX", "POD", "GR")

compute_ptdi <- function(species) {
  message("Computing PTDI for ", species)

  deg_file <- file.path(
    "results", "expression", paste0(species, "_warming_DEG_ids.txt")
  )
  assert_file(
    deg_file,
    "Warming-responsive DEG list; run R/10_prepare_deseq2_gene_sets.R first"
  )
  warming_genes <- unique(readLines(deg_file))

  # Use the same plot × species physiological source data as the manuscript.
  # Samples missing any of the seven PTDI physiological traits are excluded from
  # both molecular and physiological ordinations so the two spaces are paired.
  meta <- species_metadata(species, complete_traits = phys_traits)
  rownames(meta) <- meta$Sample

  counts <- read_count_matrix(COUNT_PATHS[[species]])
  counts <- match_matrix_to_metadata(counts, meta)

  warming_genes <- intersect(warming_genes, rownames(counts))
  if (length(warming_genes) < 2) {
    stop("Too few warming-responsive genes are present in the count matrix for ", species)
  }
  counts_sub <- counts[warming_genes, , drop = FALSE]

  # ---------------------------------------------------------------------------
  # 1. Transcriptomic space: VST + DAPC
  # ---------------------------------------------------------------------------
  dds <- DESeqDataSetFromMatrix(
    countData = counts_sub,
    colData = meta,
    design = ~ Group_Combo
  )
  vst_mat <- assay(vst(dds, blind = FALSE))
  expr_samples_by_genes <- t(vst_mat)

  n_pca <- min(20, nrow(expr_samples_by_genes) - 1, ncol(expr_samples_by_genes))
  n_da <- min(3, nlevels(meta$Group_Combo) - 1)

  dapc_res <- adegenet::dapc(
    expr_samples_by_genes,
    grp = meta$Group_Combo,
    n.pca = n_pca,
    n.da = n_da
  )

  trans_coords <- as.data.frame(dapc_res$ind.coord[, 1:2, drop = FALSE])
  names(trans_coords)[1:2] <- c("LD1", "LD2")
  trans_coords$Sample <- rownames(dapc_res$ind.coord)
  trans_coords <- trans_coords |>
    dplyr::left_join(
      meta |> dplyr::select(Sample, Warming, Watering, Block),
      by = "Sample"
    )

  # ---------------------------------------------------------------------------
  # 2. Physiological space: standardized PCA
  # ---------------------------------------------------------------------------
  phys_mat <- meta[, phys_traits, drop = FALSE]
  rownames(phys_mat) <- meta$Sample

  phys_pca <- stats::prcomp(phys_mat, center = TRUE, scale. = TRUE)
  phys_coords <- as.data.frame(phys_pca$x[, 1:2, drop = FALSE])
  names(phys_coords)[1:2] <- c("PC1", "PC2")
  phys_coords$Sample <- rownames(phys_pca$x)
  phys_coords <- phys_coords |>
    dplyr::left_join(
      meta |> dplyr::select(Sample, Warming, Watering, Block),
      by = "Sample"
    )

  # ---------------------------------------------------------------------------
  # 3. Sample-level distances to the corresponding T0 centroid
  # ---------------------------------------------------------------------------
  dist_trans <- trans_coords |>
    dplyr::group_by(Watering) |>
    dplyr::mutate(
      T0_LD1 = mean(LD1[Warming == "T0"], na.rm = TRUE),
      T0_LD2 = mean(LD2[Warming == "T0"], na.rm = TRUE),
      Dtrans = sqrt((LD1 - T0_LD1)^2 + (LD2 - T0_LD2)^2)
    ) |>
    dplyr::ungroup()

  dist_phys <- phys_coords |>
    dplyr::group_by(Watering) |>
    dplyr::mutate(
      T0_PC1 = mean(PC1[Warming == "T0"], na.rm = TRUE),
      T0_PC2 = mean(PC2[Warming == "T0"], na.rm = TRUE),
      Dphys = sqrt((PC1 - T0_PC1)^2 + (PC2 - T0_PC2)^2)
    ) |>
    dplyr::ungroup()

  ptdi <- dist_trans |>
    dplyr::select(Sample, Block, Warming, Watering, Dtrans) |>
    dplyr::left_join(
      dist_phys |> dplyr::select(Sample, Dphys),
      by = "Sample"
    ) |>
    dplyr::mutate(
      Species = species,
      PTDI = Dtrans / Dphys,
      .before = 1
    ) |>
    dplyr::filter(Warming != "T0")

  # ---------------------------------------------------------------------------
  # 4. Coordinates and centroids for Fig. S3 trajectories
  # ---------------------------------------------------------------------------
  trajectories <- dplyr::bind_rows(
    trans_coords |>
      dplyr::transmute(
        Species = species,
        Data_type = "Transcriptome",
        Sample, Block, Warming, Watering,
        Axis1 = LD1, Axis2 = LD2
      ),
    phys_coords |>
      dplyr::transmute(
        Species = species,
        Data_type = "Physiology",
        Sample, Block, Warming, Watering,
        Axis1 = PC1, Axis2 = PC2
      )
  )

  centroids <- trajectories |>
    dplyr::group_by(Species, Data_type, Watering, Warming) |>
    dplyr::summarise(
      Axis1 = mean(Axis1, na.rm = TRUE),
      Axis2 = mean(Axis2, na.rm = TRUE),
      .groups = "drop"
    ) |>
    dplyr::arrange(Species, Data_type, Watering, Warming)

  list(
    ptdi = ptdi,
    trajectories = trajectories,
    centroids = centroids,
    n_warming_genes = length(warming_genes)
  )
}

ptdi_objects <- lapply(c("Aj", "Ce"), compute_ptdi)
ptdi_all <- dplyr::bind_rows(lapply(ptdi_objects, function(x) x$ptdi))
traj_all <- dplyr::bind_rows(lapply(ptdi_objects, function(x) x$trajectories))
centroid_all <- dplyr::bind_rows(lapply(ptdi_objects, function(x) x$centroids))

readr::write_csv(ptdi_all, file.path("results", "Fig2_PTDI_recomputed.csv"))
readr::write_csv(traj_all, file.path("results", "FigS3_trajectory_coordinates_recomputed.csv"))
readr::write_csv(centroid_all, file.path("results", "FigS3_trajectory_centroids_recomputed.csv"))

# Validate recomputed Fig. 2 values against the archived source-data workbook.
source_ptdi <- read_source_table(source_sheet("ptdi")) |>
  dplyr::mutate(Species = as.character(Species), Sample = as.character(Sample))

validation <- source_ptdi |>
  dplyr::select(
    Species, Sample,
    Source_Dtrans = Dtrans,
    Source_Dphys = Dphys,
    Source_PTDI = PTDI
  ) |>
  dplyr::full_join(
    ptdi_all |>
      dplyr::select(
        Species, Sample,
        Computed_Dtrans = Dtrans,
        Computed_Dphys = Dphys,
        Computed_PTDI = PTDI
      ),
    by = c("Species", "Sample")
  ) |>
  dplyr::mutate(
    Delta_Dtrans = Computed_Dtrans - Source_Dtrans,
    Delta_Dphys = Computed_Dphys - Source_Dphys,
    Delta_PTDI = Computed_PTDI - Source_PTDI
  )

readr::write_csv(
  validation,
  file.path("results", "Fig2_PTDI_source_validation.csv")
)

# =============================================================================
# 5. Fig. 2: PTDI
# =============================================================================

p_ptdi <- ggplot(ptdi_all, aes(Warming, PTDI, fill = Watering)) +
  stat_summary(
    fun = mean, geom = "col",
    position = position_dodge(0.75), width = 0.55, alpha = 0.85
  ) +
  geom_point(
    aes(group = Watering),
    position = position_jitterdodge(jitter.width = 0.08, dodge.width = 0.75),
    size = 1.5, alpha = 0.6
  ) +
  stat_summary(
    fun.data = mean_se_df,
    geom = "errorbar",
    position = position_dodge(0.75), width = 0.15
  ) +
  geom_hline(yintercept = 1, linetype = "dashed", color = "grey50") +
  facet_wrap(~ Species, scales = "free_y", nrow = 1) +
  labs(x = "Warming treatment", y = "PTDI") +
  theme_bw(base_size = 10) +
  theme(panel.grid = element_blank(), legend.position = "top")

ggsave(file.path("figures", "Fig2_PTDI.pdf"), p_ptdi, width = 7.0, height = 3.3)

# =============================================================================
# 6. Fig. S3: transcriptomic and physiological trajectories
# =============================================================================

p_traj <- ggplot(traj_all, aes(Axis1, Axis2)) +
  geom_point(aes(color = Watering), alpha = 0.25, size = 1.2) +
  geom_path(
    data = centroid_all,
    aes(group = Watering, color = Watering),
    arrow = arrow(length = grid::unit(0.18, "cm")),
    linewidth = 0.7
  ) +
  geom_point(data = centroid_all, aes(color = Watering), size = 2.4) +
  ggrepel::geom_text_repel(data = centroid_all, aes(label = Warming), size = 3) +
  facet_grid(Species ~ Data_type, scales = "free") +
  labs(x = "Axis 1", y = "Axis 2") +
  theme_bw(base_size = 9) +
  theme(panel.grid = element_blank(), legend.position = "top")

ggsave(
  file.path("figures", "FigS3_multivariate_trajectories.pdf"),
  p_traj, width = 7.2, height = 6.2
)
